# Generated by Django 4.2.7 on 2025-09-06 09:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('threat_type', models.CharField(max_length=100)),
                ('actor', models.CharField(blank=True, max_length=200)),
                ('target_sectors', models.JSONField(blank=True, default=list)),
                ('target_countries', models.JSONField(blank=True, default=list)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_ongoing', models.BooleanField(default=True)),
                ('severity_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('affected_organizations', models.PositiveIntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('references', models.JSONField(blank=True, default=list)),
                ('iocs', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campagne de menace',
                'verbose_name_plural': 'Campagnes de menace',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ThreatIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_type', models.CharField(choices=[('ip', 'Adresse IP'), ('domain', 'Nom de domaine'), ('url', 'URL'), ('email', 'Adresse email'), ('hash_md5', 'Hash MD5'), ('hash_sha1', 'Hash SHA1'), ('hash_sha256', 'Hash SHA256'), ('filename', 'Nom de fichier'), ('cve', 'CVE'), ('malware_family', 'Famille de malware'), ('other', 'Autre')], max_length=50)),
                ('value', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('confidence', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], default='medium', max_length=20)),
                ('threat_type', models.CharField(blank=True, max_length=100)),
                ('malware_family', models.CharField(blank=True, max_length=100)),
                ('campaign', models.CharField(blank=True, max_length=200)),
                ('actor', models.CharField(blank=True, max_length=200)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('references', models.JSONField(blank=True, default=list)),
                ('severity_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('impact_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_false_positive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Indicateur de menace',
                'verbose_name_plural': 'Indicateurs de menace',
                'ordering': ['-first_seen'],
            },
        ),
        migrations.CreateModel(
            name='ThreatSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('source_type', models.CharField(choices=[('misp', 'MISP'), ('cert_fr', 'CERT-FR'), ('osint', 'OSINT'), ('commercial', 'Commercial'), ('government', 'Gouvernemental'), ('internal', 'Interne'), ('other', 'Autre')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('api_endpoint', models.URLField(blank=True)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_frequency_hours', models.PositiveIntegerField(default=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Source de threat intelligence',
                'verbose_name_plural': 'Sources de threat intelligence',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ThreatIntelligenceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('daily', 'Rapport quotidien'), ('weekly', 'Rapport hebdomadaire'), ('monthly', 'Rapport mensuel'), ('ad_hoc', 'Rapport ad-hoc'), ('incident', "Rapport d'incident")], max_length=50)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('severity_level', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('references', models.JSONField(blank=True, default=list)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target_clients', models.ManyToManyField(blank=True, related_name='threat_reports', to='accounts.client')),
                ('threat_campaigns', models.ManyToManyField(blank=True, related_name='reports', to='threat_intelligence.threatcampaign')),
                ('threat_indicators', models.ManyToManyField(blank=True, related_name='reports', to='threat_intelligence.threatindicator')),
            ],
            options={
                'verbose_name': 'Rapport de threat intelligence',
                'verbose_name_plural': 'Rapports de threat intelligence',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreatIntelligenceFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('feed_type', models.CharField(choices=[('ioc', 'Indicators of Compromise'), ('malware', 'Malware'), ('phishing', 'Phishing'), ('vulnerability', 'Vulnérabilités'), ('apt', 'APT'), ('general', 'Général')], max_length=50)),
                ('url', models.URLField()),
                ('format', models.CharField(default='json', max_length=50)),
                ('update_frequency', models.PositiveIntegerField(default=3600)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_process', models.BooleanField(default=True)),
                ('filter_rules', models.JSONField(blank=True, default=dict)),
                ('mapping_rules', models.JSONField(blank=True, default=dict)),
                ('total_indicators', models.PositiveIntegerField(default=0)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('last_success', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='threat_intelligence.threatsource')),
            ],
            options={
                'verbose_name': 'Flux de threat intelligence',
                'verbose_name_plural': 'Flux de threat intelligence',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='threatindicator',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='threat_intelligence.threatsource'),
        ),
        migrations.CreateModel(
            name='ThreatCorrelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_type', models.CharField(choices=[('ip_match', 'Correspondance IP'), ('domain_match', 'Correspondance domaine'), ('hash_match', 'Correspondance hash'), ('email_match', 'Correspondance email'), ('pattern_match', 'Correspondance de pattern'), ('behavioral_match', 'Correspondance comportementale')], max_length=50)),
                ('confidence_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('matched_value', models.CharField(max_length=500)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_false_positive', models.BooleanField(default=False)),
                ('verification_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threat_correlations', to='accounts.client')),
                ('threat_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlations', to='threat_intelligence.threatindicator')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_correlations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Corrélation de menace',
                'verbose_name_plural': 'Corrélations de menace',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='threatcampaign',
            name='indicators',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='threat_intelligence.threatindicator'),
        ),
        migrations.AddIndex(
            model_name='threatindicator',
            index=models.Index(fields=['indicator_type', 'value'], name='threat_inte_indicat_3a3d1d_idx'),
        ),
        migrations.AddIndex(
            model_name='threatindicator',
            index=models.Index(fields=['threat_type'], name='threat_inte_threat__b5e55a_idx'),
        ),
        migrations.AddIndex(
            model_name='threatindicator',
            index=models.Index(fields=['confidence'], name='threat_inte_confide_26f988_idx'),
        ),
        migrations.AddIndex(
            model_name='threatindicator',
            index=models.Index(fields=['first_seen'], name='threat_inte_first_s_4d5aa9_idx'),
        ),
        migrations.AddIndex(
            model_name='threatindicator',
            index=models.Index(fields=['is_active'], name='threat_inte_is_acti_c8abc3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='threatindicator',
            unique_together={('source', 'indicator_type', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='threatcorrelation',
            unique_together={('client', 'threat_indicator', 'correlation_type', 'matched_value')},
        ),
    ]
