# Generated by Django 4.2.7 on 2025-09-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usersession_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='session_key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
