# Generated by Django 4.2.7 on 2025-09-06 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('paused', 'En pause'), ('archived', 'Archivé')], default='draft', max_length=20)),
                ('trigger_type', models.CharField(choices=[('alert_created', 'Alerte créée'), ('alert_updated', 'Alerte mise à jour'), ('incident_created', 'Incident créé'), ('incident_updated', 'Incident mis à jour'), ('risk_score_threshold', 'Seuil de score de risque'), ('time_based', 'Basé sur le temps'), ('manual', 'Manuel')], max_length=50)),
                ('trigger_conditions', models.JSONField(blank=True, default=dict)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
                ('max_execution_time', models.PositiveIntegerField(default=3600)),
                ('retry_count', models.PositiveIntegerField(default=3)),
                ('retry_delay', models.PositiveIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_executed', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbooks', to='accounts.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_playbooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Playbook SOAR',
                'verbose_name_plural': 'Playbooks SOAR',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlaybookExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(max_length=50)),
                ('trigger_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_time', models.PositiveIntegerField(blank=True, null=True)),
                ('steps_completed', models.PositiveIntegerField(default=0)),
                ('total_steps', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('logs', models.TextField(blank=True)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playbook_executions', to=settings.AUTH_USER_MODEL)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='soar.playbook')),
            ],
            options={
                'verbose_name': 'Exécution de playbook',
                'verbose_name_plural': 'Exécutions de playbook',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SOARLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Avertissement'), ('error', 'Erreur'), ('critical', 'Critique')], max_length=20)),
                ('message', models.TextField()),
                ('component', models.CharField(max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soar_logs', to='accounts.client')),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soar_logs', to='soar.playbookexecution')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soar_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log SOAR',
                'verbose_name_plural': 'Logs SOAR',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('integration_type', models.CharField(choices=[('firewall', 'Pare-feu'), ('siem', 'SIEM'), ('email', 'Email'), ('slack', 'Slack'), ('webhook', 'Webhook'), ('api', 'API REST'), ('ldap', 'LDAP/Active Directory'), ('ticketing', 'Système de tickets'), ('other', 'Autre')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('base_url', models.URLField(blank=True)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('username', models.CharField(blank=True, max_length=200)),
                ('password', models.CharField(blank=True, max_length=500)),
                ('additional_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_healthy', models.BooleanField(default=True)),
                ('last_test', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intégration',
                'verbose_name_plural': 'Intégrations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(choices=[('alert_risk_score', "Score de risque d'alerte"), ('alert_severity', "Sévérité d'alerte"), ('alert_type', "Type d'alerte"), ('incident_priority', "Priorité d'incident"), ('time_based', 'Basé sur le temps'), ('custom', 'Personnalisé')], max_length=50)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
                ('execution_delay', models.PositiveIntegerField(default=0)),
                ('trigger_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='accounts.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_automation_rules', to=settings.AUTH_USER_MODEL)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='soar.playbook')),
            ],
            options={
                'verbose_name': "Règle d'automatisation",
                'verbose_name_plural': "Règles d'automatisation",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('action_type', models.CharField(choices=[('email_notification', 'Notification email'), ('slack_notification', 'Notification Slack'), ('create_ticket', 'Créer un ticket'), ('assign_alert', 'Assigner une alerte'), ('block_ip', 'Bloquer une IP'), ('quarantine_file', 'Mettre en quarantaine un fichier'), ('update_status', 'Mettre à jour le statut'), ('add_comment', 'Ajouter un commentaire'), ('escalate', 'Escalader'), ('webhook', 'Webhook'), ('script', 'Script personnalisé')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('integration_config', models.JSONField(blank=True, default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Action SOAR',
                'verbose_name_plural': 'Actions SOAR',
                'ordering': ['name'],
            },
        ),
    ]
